# Generated by Django 5.2 on 2025-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews_qty',
            field=models.FloatField(),
        ),
    ]
